<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{78901d43-390c-49e4-8828-9e45bd511c66}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nisse: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nisse:=nisse;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>