<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="POU_2" Id="{3eb8aa00-9a33-483d-b7d8-e09c1dffc10f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU_2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>