<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="POU_1" Id="{c2aa6c9c-86dd-479a-8f09-745281c27c6e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU_1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>